version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '1234'
    volumes:
      - pgdatavolume:/var/lib/postgresql/data
    restart: always

volumes:
  pgdatavolume:
